# Vector Operations

In [1]:
import numpy as np

In [2]:
A = np.array([1+1j, 2+2j, 3+3j, 4+4j, 5+5j])
B = np.array([6-6j, 7-7j, 8-8j, 9-9j, 10-10j])
C = np.array([2,3,5,7,11])
Z = np.array([0,0,0,0,0])

In [3]:
A

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j, 5.+5.j])

In [4]:
B

array([ 6. -6.j,  7. -7.j,  8. -8.j,  9. -9.j, 10.-10.j])

In [5]:
C

array([ 2,  3,  5,  7, 11])

In [6]:
Z

array([0, 0, 0, 0, 0])

## Operations

### Equality

In [7]:
A == A

array([ True,  True,  True,  True,  True])

In [8]:
np.array_equal(A, A)

True

In [9]:
np.array_equal(A, B)

False

### Addition

In [10]:
A + B

array([ 7.-5.j,  9.-5.j, 11.-5.j, 13.-5.j, 15.-5.j])

In [11]:
A + (B + C) == (A + B) + C

array([ True,  True,  True,  True,  True])

In [12]:
A == A + 0

array([ True,  True,  True,  True,  True])

In [13]:
np.array_equal( 
    A + B,
    [ A[n] + B[n] for n in range(0,len(A))  ]
)

True

In [14]:
np.array_equal( 
    A + 1,
    [ A[n] + 1 for n in range(0,len(A))  ]
)

True

In [15]:
A + B == B + A

array([ True,  True,  True,  True,  True])

### Subtraction

In [16]:
A - B

array([-5. +7.j, -5. +9.j, -5.+11.j, -5.+13.j, -5.+15.j])

In [17]:
A - B == B - A

array([False, False, False, False, False])

In [18]:
A - (B + C) == A - B - C

array([ True,  True,  True,  True,  True])

In [19]:
np.array_equal( 
    A,
    A - 0,
)

True

In [20]:
np.array_equal( 
    A - B,
    [ A[n] - B[n] for n in range(0,len(A))  ]
)

True

In [21]:
np.array_equal( 
    A - 1,
    [ A[n] - 1 for n in range(0,len(A))  ]
)

True

### Multiplicaton

In [22]:
A * B

array([ 12.+0.j,  28.+0.j,  48.+0.j,  72.+0.j, 100.+0.j])

In [23]:
A * 1 == A

array([ True,  True,  True,  True,  True])

In [24]:
-A == A * -1

array([ True,  True,  True,  True,  True])

In [25]:
np.array_equal( 
    A * 5,
    [ A[n] * 5 for n in range(0,len(A))  ]
)

True

In [26]:
np.array_equal( 
    A * B,
    [ A[n] * B[n] for n in range(0,len(A))  ]
)

True

### Division

In [27]:
A / B

array([0.+0.16666667j, 0.+0.28571429j, 0.+0.375j     , 0.+0.44444444j,
       0.+0.5j       ])

In [28]:
np.array_equal( 
    A / 5,
    [ A[n] / 5 for n in range(0,len(A))  ]
)

True

In [29]:
np.array_equal( 
    A / B,
    [ A[n] / B[n] for n in range(0,len(A))  ]
)

True

### Prove (c1 + c2) · V == c1 · V + c2 · V

((c1 + c2)*V)[j]             
= (c1 + c2)*(V[j])           
= (c1 * V[j]) + (c2 * V[j])  
= (c1 * V)[j] + (c2 * V)[j]   
= ((c1 * V) + (c2 * V))[j]

In [30]:
c1 = 3+4j
c2 = 7-8j

In [31]:
np.array_equal( 
    (c1 + c2) * A,
    (c1 * A) + (c2 * A)
)

True

In [32]:
np.array_equal( 
    [ (c1 + c2) * A[n] for n in range(0,len(A))  ],
    [ (c1 * A[n]) + (c2 * A[n]) for n in range(0,len(A))  ]
)

True