# Hadamard Matrix

In [3]:
import numpy as np

### Identity Matrix

In [6]:
I = np.matrix([[1,0],[0,1]]); I

matrix([[1, 0],
        [0, 1]])

### Hadamard Matrix

In [19]:
H = 1/np.sqrt(2) * np.matrix([[1,1],[1,-1]]); H

matrix([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]])

The dot product of the Hadamard Matrix with itself is the identity matrix

In [20]:
np.dot(H,H)

matrix([[ 1.00000000e+00, -2.23711432e-17],
        [-2.23711432e-17,  1.00000000e+00]])

In [33]:
np.matrix.round(np.dot(H,H), 15)

array([[ 1., -0.],
       [-0.,  1.]])

In [34]:
np.matrix.round(np.dot(H,H), 15) == I

matrix([[ True,  True],
        [ True,  True]])